services:
  reverseproxy:
    #image: nginx:latest
    build:
      context: ../.
      dockerfile: source/nginx/Dockerfile
    container_name: airbyte-reverseproxy
    restart: unless-stopped
    networks:
      - backend
    ports:
      - 8000:8000
      - 443:443

networks:
  backend:
    name: airbyte-backend