services:
  reverseproxy:
    image: nginx:latest
    container_name: airbyte-reverseproxy
    restart: unless-stopped
    networks:
      - backend
    ports:
      - 80:80
      - 443:443

networks:
  backend:
    name: airbyte-backend